app:
    resource: "@AppBundle/Controller/"
    type:     annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
    prefix: /secure

no_controller:
    path: /no-controller
    defaults:
        _controller: FrameworkBundle:Template:template
        template:    default/no_controller.html.twig