# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:

    app.tasks_limit_not_reached_validator:
        class: AppBundle\Validator\Constraints\TasksLimitNotReachedValidator
        tags:
            - { name: validator.constraint_validator }

    app.can_change_task_status_voter:
        class: AppBundle\Security\Voter\CanChangeTaskStatusVoter
        tags:
            - { name: security.voter }
        public: false

    app.service_a:
        class: AppBundle\Service\MyServiceA
        arguments:
            - "@app.service_b"

    app.service_b:
        class: AppBundle\Service\MyServiceB

    app.service_a_factory:
        class: AppBundle\Service\MyServiceAFactory

    app.service_a_from_factory:
        class: AppBundle\Service\MyServiceA
        factory:
            - '@app.service_a_factory'
            - create
        arguments:
            - "@app.service_b"

    app.service_b_lazy_loaded:
        class: AppBundle\Service\MyServiceB

    app.service_with_lazy_dep:
        class: AppBundle\Service\MyServiceWithLazyDependency
        arguments:
            - "@app.service_b_lazy_loaded"